#!/usr/bin/env python3
"""Convert scripts/presets/presets_<group>.gd into docs/js/presets-generated.js.

The preset files are a narrow subset of GDScript (static funcs returning
dictionary literals built with helper calls and .merge), so a line-based
translation is enough. Re-run after editing any preset:

    python3 tools/convert_presets.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PRESET_DIR = ROOT / "scripts" / "presets"
OUT = ROOT / "docs" / "js" / "presets-generated.js"

FUNC_RE = re.compile(r"^static func (\w+)\((.*)\)\s*->\s*\w+:\s*$")
VAR_RE = re.compile(r"\bvar (\w+)\s*(?::\s*[\w\[\]]+)?\s*:?=\s*")
MERGE_RE = re.compile(r"\b(\w+)\.merge\(")


def split_comment(line):
    """Return (code, comment) splitting on the first # outside a string."""
    in_str = None
    for i, ch in enumerate(line):
        if in_str:
            if ch == in_str:
                in_str = None
        elif ch in "\"'":
            in_str = ch
        elif ch == "#":
            return line[:i], line[i + 1:]
    return line, None


def convert_args(args):
    out = []
    for a in filter(None, (x.strip() for x in args.split(","))):
        a = re.sub(r":\s*[\w\[\]]+", "", a)
        out.append(a)
    return ", ".join(out)


def close_func(lines_out):
    """Close the open function, keeping blank lines after the brace."""
    blanks = 0
    while lines_out and not lines_out[-1].strip():
        lines_out.pop()
        blanks += 1
    lines_out.append("}")
    lines_out.extend([""] * blanks)


def convert_file(path):
    funcs = []
    lines_out = []
    in_func = False
    merging = False
    for raw in path.read_text().splitlines():
        if raw.startswith(("class_name", "extends")):
            continue
        code, comment = split_comment(raw)
        top_level = raw.strip() and not raw[0].isspace()
        if in_func and top_level:
            close_func(lines_out)
            in_func = False
        m = FUNC_RE.match(code.strip()) if top_level else None
        if m:
            name, args = m.groups()
            funcs.append(name)
            lines_out.append(f"function {name}({convert_args(args)}) {{")
            in_func = True
            continue
        code = VAR_RE.sub(r"let \1 = ", code)
        if MERGE_RE.search(code):
            merging = True
        code = MERGE_RE.sub(r"Object.assign(\1, ", code)
        # GDScript's merge(d, true) overwrite flag has no Object.assign
        # equivalent (assign always overwrites) — drop it.
        if merging and code.rstrip().endswith(", true)"):
            code = code.rstrip()[: -len(", true)")] + ")"
            merging = False
        code = code.replace("\t", "  ")
        if comment is not None:
            code = f"{code}//{comment}"
        lines_out.append(code.rstrip())
    if in_func:
        close_func(lines_out)
    return funcs, lines_out


def main():
    registry = json.loads((PRESET_DIR / "registry.json").read_text())
    groups = []
    for entry in registry:
        if entry["group"] not in groups:
            groups.append(entry["group"])

    parts = [
        "// GENERATED by tools/convert_presets.py from scripts/presets/*.gd.",
        "// Do not edit by hand — edit the GDScript and re-run the converter.",
        "/* eslint-disable */",
        "import {",
        "  _rand, _rand_int, _pick, _apply_target, _off_with,",
        "  SQR, SAW, TRI, SIN, NSE, PNK, BRN, LP, HP, BP,",
        "  _layer, _sound, _env, _filt, _drive, _bend, _vib, _trem, _pulses,",
        "  _at, _arp, _echo, _crush, _flange, _chord,",
        "} from './presets-helpers.js';",
        "",
        f"export const REGISTRY = {json.dumps(registry, indent=2)};",
        "",
        "export const GROUPS = {};",
    ]
    for group in groups:
        fname = "presets_" + group.lower().replace("-", "_") + ".gd"
        funcs, body = convert_file(PRESET_DIR / fname)
        parts.append("")
        parts.append(f"// ── {group} ({fname}) " + "─" * 20)
        parts.append(f"GROUPS[{json.dumps(group)}] = (() => {{")
        parts.extend(("  " + l) if l else "" for l in body)
        parts.append(f"  return {{ {', '.join(funcs)} }};")
        parts.append("})();")
    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(groups)} groups)")


if __name__ == "__main__":
    main()
